#ifndef LEITURAFICHEIROS
#define LEITURAFICHEIROS

#define MAXLINHAS 10000000
#define MAX_BUFFER_VENDAS 64
#define MAX_BUFFER_CATALOGO 32

extern int STATUS;

void argumentosMain(int, const char **);
int abrirFicheirosInit(CATALOGO_CLIENTES,CATALOGO_PRODUTOS,MODULO_GESTAO_FILIAIS,MODULO_FATURACAO);

#endif /* LEITURAFICHEIROS */
